version: "3.4"
services:
  nginx:
    image: nginx:1.18.0-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www
    ports:
      - "7777:80"
    depends_on:
      - app
  app:
    build: .
    volumes:
      - .:/app
    command: /bin/bash -c "npm run watch"
